//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PodCraze.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PodCrazeEntities2 : DbContext
    {
        public PodCrazeEntities2()
            : base("name=PodCrazeEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<Listener> Listeners { get; set; }
        public virtual DbSet<ListenerReq> ListenerReqs { get; set; }
        public virtual DbSet<Narrator> Narrators { get; set; }
        public virtual DbSet<Podcast> Podcasts { get; set; }
    }
}
